workflows:
  ios-release-no-shorebird:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Build for iOS Simulator
        script: |
          flutter clean
          flutter pub get
          flutter build ios --simulator

      - name: Archive Simulator Build
        script: |
          mkdir -p build/ios/ipa
          zip -r build/ios/ipa/Runner.app.zip build/ios/iphonesimulator/Runner.app

    artifacts:
      - build/ios/ipa/Runner.app.zip
