workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: 3.19.6
      xcode: latest
      groups:
        - google_credentials
      vars:
        FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
    scripts:
      - name: Set up Flutter
        script: |
          flutter packages pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: 3.19.6
      xcode: latest
      groups:
        - google_credentials
      vars:
        FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
    scripts:
      - name: Set up Flutter
        script: |
          flutter packages pub get
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
