workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: 3.19.6
      xcode: latest
      java: 11
    scripts:
      - name: Set up Flutter
        script: |
          flutter clean
          flutter pub get
      - name: Build Android APK
        script: |
          # Print environment information for debugging
          flutter doctor -v
          
          # Build release APK
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
