workflows:
  ios-simulator:
    name: iOS Simulator Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios && pod install && cd ..
      - name: Build for iOS simulator
        script: |
          flutter build ios --debug --no-codesign --simulator
          
          cd build/ios/Debug-iphonesimulator
          mkdir -p ../ipa
          zip -r ../ipa/Runner.app.zip Runner.app
    artifacts:
      - build/ios/ipa/Runner.app.zip