// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSVryFNxcByJW0fcZT9W1lUzVpIWnXWw8',
    appId: '1:683472925715:web:796dee14b3798a53c83be6',
    messagingSenderId: '683472925715',
    projectId: 'travel-app-6152a',
    authDomain: 'travel-app-6152a.firebaseapp.com',
    storageBucket: 'travel-app-6152a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO-l8ms3BGeNSlXsfdMnXNsgixLYjgljk',
    appId: '1:683472925715:android:7fccc8a941dbbfe9c83be6',
    messagingSenderId: '683472925715',
    projectId: 'travel-app-6152a',
    storageBucket: 'travel-app-6152a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcHFbw0PG9X-RoN2ObjfdrB2Noi9deAzU',
    appId: '1:683472925715:ios:022e02c0c7c4e5e3c83be6',
    messagingSenderId: '683472925715',
    projectId: 'travel-app-6152a',
    storageBucket: 'travel-app-6152a.firebasestorage.app',
    iosBundleId: 'com.example.cpmdEndterm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcHFbw0PG9X-RoN2ObjfdrB2Noi9deAzU',
    appId: '1:683472925715:ios:022e02c0c7c4e5e3c83be6',
    messagingSenderId: '683472925715',
    projectId: 'travel-app-6152a',
    storageBucket: 'travel-app-6152a.firebasestorage.app',
    iosBundleId: 'com.example.cpmdEndterm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSVryFNxcByJW0fcZT9W1lUzVpIWnXWw8',
    appId: '1:683472925715:web:00d1545720a95436c83be6',
    messagingSenderId: '683472925715',
    projectId: 'travel-app-6152a',
    authDomain: 'travel-app-6152a.firebaseapp.com',
    storageBucket: 'travel-app-6152a.firebasestorage.app',
  );
}
