// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4uUylwk6NmfaKwrNKhL2JzfUZbBrli3k',
    appId: '1:896068345728:web:1445a01083f2eed47e6b65',
    messagingSenderId: '896068345728',
    projectId: 'cursor-33623',
    authDomain: 'cursor-33623.firebaseapp.com',
    storageBucket: 'cursor-33623.firebasestorage.app',
    measurementId: 'G-X1R90F7VBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT6qpiBtUgBldiMzXYwveT0r3MYAw2-UU',
    appId: '1:896068345728:android:039718dde54d22997e6b65',
    messagingSenderId: '896068345728',
    projectId: 'cursor-33623',
    storageBucket: 'cursor-33623.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcRlZfTYz_bPNBie6hTOXb0XE4H3Wwbgo',
    appId: '1:896068345728:ios:61d18de2457d576b7e6b65',
    messagingSenderId: '896068345728',
    projectId: 'cursor-33623',
    storageBucket: 'cursor-33623.firebasestorage.app',
    iosBundleId: 'com.travelapp.travelManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcRlZfTYz_bPNBie6hTOXb0XE4H3Wwbgo',
    appId: '1:896068345728:ios:61d18de2457d576b7e6b65',
    messagingSenderId: '896068345728',
    projectId: 'cursor-33623',
    storageBucket: 'cursor-33623.firebasestorage.app',
    iosBundleId: 'com.travelapp.travelManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4uUylwk6NmfaKwrNKhL2JzfUZbBrli3k',
    appId: '1:896068345728:web:3a32f93cccc44d947e6b65',
    messagingSenderId: '896068345728',
    projectId: 'cursor-33623',
    authDomain: 'cursor-33623.firebaseapp.com',
    storageBucket: 'cursor-33623.firebasestorage.app',
    measurementId: 'G-G1JF8Z76TP',
  );
}
